#pragma once
#include "Versioning.h" // this file is generated by CMAKE during build process
// ------------Audio -----------------
const float g_desired_blocksize_ms(20); // its in ms to be independent from the sampling rate
const bool g_forcePowerOf2(true); // should be true for FFT Processing

// -------------- GUI -----------------
// global GUI setting for JadeSpectrogram
const int g_minGuiSize_x(800);
const int g_maxGuiSize_x(1400);
const int g_minGuiSize_y(550);
const float g_guiratio = float(g_minGuiSize_y)/g_minGuiSize_x;

// ---------- presethandler ----------
//const StringArray g_PresetCategories("Unknown", "Lead", "Brass", "Template", "Bass",
//	"Key", "Organ" , "Pad", "Drums_Perc", "SpecialEffect","Sequence", "String" );
const juce::StringArray g_PresetCategories(""); // keep empty for "no categories"

const int g_minPresetHandlerHeight(30); // in pixels
#define MIN_COMBO_WITH_PRESET 120
#define MIN_ELEMENT_DIST_PRESET 10
#define MIN_BUTTON_WIDTH_PRESET 40
#define MIN_ELEMENT_HEIGHT_PRESET 20

// ------- Midi Keyboard display-------
const float g_midikeyboardratio(0.13f); // in percent of height()
const float g_wheelstokeyboardratio(0.1f);

// -------Your defines for GUI --------
const int g_spec_x(5);
const int g_spec_y(35);

const int g_spec_width(790);
const int g_spec_height(510);

// Slider
const int g_FreqMeter(40);
const int g_SliderWidth(20);
const int g_SliderHeight(200);

const int g_menuHeight(20);

// PosFreqSlider
const int g_SliderMinFreq_x(2);
const int g_SliderMinFreq_y(240);

const int g_SliderMaxFreq_x(2);
const int g_SliderMaxFreq_y(10);

const int g_SliderMaxColor_x(g_spec_width - g_SliderWidth-g_SliderMinFreq_x);
const int g_SliderMaxColor_y(g_SliderMaxFreq_y);

const int g_SliderMinColor_x(g_spec_width - g_SliderWidth-g_SliderMinFreq_x);
const int g_SliderMinColor_y(g_SliderMinFreq_y);


const int g_colorbar_width(30);

const float g_maxColorVal(20.0);
const float g_minColorVal(-80.0);

const int g_ButtonHeight(g_menuHeight);
const int g_ButtonWidth(50);
const int g_PauseButton_x(g_FreqMeter+g_SliderWidth+g_SliderMinFreq_x);
const int g_PauseButton_y(g_spec_height-g_menuHeight);

